# Generated by Django 4.1.13 on 2024-05-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sports", "SPORTS"),
                    ("Technology", "TECHNOLOGY"),
                    ("Entertainment", "ENTERTAINMENT"),
                ],
                max_length=20,
            ),
        ),
    ]
