# Generated by Django 4.1.13 on 2024-05-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sports", "SPORTS"),
                    ("Technology", "TECHNOLOGY"),
                    ("Entertainment", "ENTERTAINMENT"),
                    ("Politics", "POLITICS"),
                    ("Health", "HEALTH"),
                    ("Education", "EDUCATION"),
                ],
                max_length=20,
            ),
        ),
    ]
