# Generated by Django 4.1.13 on 2024-05-06 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commission_user', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='commissionuser',
            unique_together={('commission', 'user')},
        ),
    ]
